### ISSUE TITLE
ordering of operations

### ISSUE THREAD

**Issue by topepo** [tidymodels/workflows#1]
I spoke with H about this. He thought that keeping the order in which people made the specification would be appropriate. For example, for these theoretical operations:

```r
library(workflows)

wflow <-
  workflow() %>% 
  add_recipe(a_recipe) %>% 
  add_model(some_parsnip_thing) %>% 
  add_prob_calibration(method = "LDA") %>%       # <- works on class probs
  add_monotone_constraint(method = "PAVA") %>%   # <- works on class probs
  add_prob_threshold(0.75)
```

We would set the calibration to account before the monotone correction. We would also need to think of ways of removing these operations too so that someone could redefine the order by eliminating (then re-adding) operations. 

He also though that using `set_model()` made more sense then `add_model()` since a workflow _always_ needs a model.

**Comment by DavisVaughan** [comment]
We can think about this again when we start implementing these
