### ISSUE TITLE
A function to automatically document the workflow (for auditing, etc)

### ISSUE THREAD

**Issue by dkgaraujo** [tidymodels/workflows#129]
## Automatic documentation of fitted workflow objects

In many situations (especially in the corporate world), models must be documented to allow for proper model governance aspects, such as auditability and replicability. My proposal is that the `{workflows}` package incorporate a `stage` that represents the creation of a documentation file encompassing important aspects of the whole workflow. Documentation of a model in a separate file would make available information on the model to a broader set of stakeholders that are not necessarily conversant with reading code and running reproducible examples. For example, in companies such a file could be of interest to internal audit functions, managers, etc. Consistent with the contributing guidelines, I am filing a feature request issue in advance to ensure maintainers would be open to considering incorporating this feature before any PR is opened.

More specifically, such a documentation as proposed would be called on a fitted workflow object, and would produce the following effects:
* tag the object as being documented, and record the state of the fitted workflow when this documentation was done; and
* write a file in the desired path containing a number of important information, described below.

The file could theoretically be written in the main common documentation formats that are used by a broad set of users, such as PDF, HTML or docx files. The information on the fitted workflow that I suppose could be useful to include would comprise:
* the full result from the `print()` function when the argument is a fitted workflow model; plus
* information on the input objects such as number of columns, their names, and their types (so that outside reviewers understand the basics of the datasets that go into the model); plus
* a timestamp of the documentation, accompanied possibly by information such as the user, system as well as the versions of the relevant packages used as engines; plus
* a field with open commentary to be filled by the analyst that fitted the workflow model.

Ideally the documentation stage would retain the exact state of the workflow object as it was fitted, such that any further updates that change the same workflow object raise to the user upon fitting that its documentation is no longer up-to-date, inviting the user to update the documentation.

A secondary but potentially useful change, if the above proposal is incorporated, is to also include a parameter in the `fit()` method that, if set to `TRUE`, would by itself document the function after it is fitted, minimising the need for the user to include a separate line for this.

In summary, the changes to the API would broadly be the following:
* inclusion of functions tentatively called `create_doc()` and `update_doc()`; and
* (not necessary but nice to have) inclusion of an argument `doc_after_fit` in the `fit()` function.

Potential tests could include:
* test whether passing a non-fitted workflow to either of the API functions named above would abort with a message calling for a fitted workflow;
* test whether a previously undocumented fitted workflow successfully generates documentation and flags this as a `stage`;
* test whether a previously documented fitted workflow updates;
* test whether a previously documented fitted workflow recognises the need to update the documentation when any other stage of the workflow is updated, but not when it is "updated" passing the same parameters.

Subject to maintainers' acceptance and suggestions/guidance on the above, I would be happy to work and potentially propose a PR in this direction, although I cannot promise speed.

**Comment by topepo** [comment]
I think that the scope of this would require an additional package. Also, I don't think that we would alter any of the current generics (e.g. `fit()`). 

Have you even created an R package? I think that most of this is do-able but it has a large enough scope that we would not work on it for quite a while. I suspect the best approach would be to create your own R package.

**Comment by topepo** [comment]
@juliasilge pointed out this tidymodels/vetiver#53, which may be relevant for what you are describing. It won't have the validation peices that you are looking for but might be helpful.

**Comment by dkgaraujo** [comment]
Thanks @topepo - I appreciate the feedback. Indeed, it does make sense to have it as a separate package. I was initially divided between drafting a package or proposing to add a function, so I can definitely see the advantages of that approach.

I have written R packages, though none for public consumption so far (actually I am looking into publishing my first one this month). By the way, thanks for sharing @juliasilge's comment on the model scorecard - indeed this is more or less what I was going for.

If/when I have a first package I plan to share the link here just in case it could be helpful to anyone is following this debate.

Thanks very much again.
