### ISSUE TITLE
fit.workflow() errors uninformatively if mode is required but not set

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/workflows#160]
``` r
library(tidymodels)

bag_spec <- decision_tree() %>%
  set_engine("C5.0")

workflow(mpg ~ ., bag_spec) %>% 
  fit(mtcars)
#> Error in `pull_workflow_spec_encoding_tbl()`:
#> ! Exactly 1 model/engine/mode combination must be located.
#> ℹ This is an internal error in the workflows package, please report it to the package authors.
```

**Comment by DavisVaughan** [comment]
`pull_workflow_spec_encoding_tbl()` is used by `finalize_workflow()`, which is only called from `.fit_pre()`. I think `.fit_pre()` could have another check after `validate_has_model()` called `validate_model_has_mode(workflow)` that checks that the model has set the mode to something other than `"unknown"`.

We'd also update that comment to mention that the `mode` has to be finalized before `finalize_workflow()` is called too

https://github.com/tidymodels/workflows/blob/822f144e8ed8385e81150c4e8039d1bf8a9506b3/R/fit.R#L128-L132

**Comment by DavisVaughan** [comment]
With #164, the error happens as soon as you try to add the model spec with an unknown mode to the workflow

``` r
library(tidymodels)

bag_spec <- decision_tree() %>%
  set_engine("C5.0")

workflow(mpg ~ ., bag_spec)
#> Error in `add_model()` at workflows/R/workflow.R:71:4:
#> ! `spec` must have a known mode.
#> ℹ Set the mode of `spec` by using `parsnip::set_mode()` or by setting the mode directly in the parsnip specification function.
```

<sup>Created on 2022-08-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
