### ISSUE TITLE
`new_action_model` errors point out `add_model` as calling env regardless of interface

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workflows#177]
At least in `new_action_model()`, the `call` argument in errors isn't sensitive to which interface for adding model specs was used—the header calls out `add_model()` regardless:

``` r
library(parsnip)
library(workflows)

workflow() %>% add_model(boost_tree())
#> Error in `add_model()`:
#> ! `spec` must have a known mode.
#> ℹ Set the mode of `spec` by using `parsnip::set_mode()` or by setting the mode directly in the parsnip specification function.
workflow(spec = boost_tree())
#> Error in `add_model()`:
#> ! `spec` must have a known mode.
#> ℹ Set the mode of `spec` by using `parsnip::set_mode()` or by setting the mode directly in the parsnip specification function.
```

<sup>Created on 2022-09-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
I think this is ok actually. `add_model()` is a top level function and we don't want to add a `call` arg to it to be able to pass the error call through any more.

I think we mainly want to ensure that we say that an error happened in a function that users should be familiar with, which is happening here

**Comment by simonpcouch** [comment]
That makes sense! I'm with it—will go ahead and close this issue.
