### ISSUE TITLE
a note about predicting with recipes

### ISSUE THREAD

**Issue by topepo** [tidymodels/workflows#178]
One common issue that I see is that people using recipes will use `bake()` on the data then feed that to `predict.workflow()`. Example: https://community.rstudio.com/t/applying-predict-on-a-new-baked-dataframe-returns-error-replacement-has-8-rows-data-has-7/147917/6

Can we put an explicit "you don't need to do this" into the man file for `predict.workflows()`?

**Comment by DavisVaughan** [comment]
It is technically mentioned here
https://github.com/tidymodels/workflows/blob/2513121aebab1564970999d2380b98fbff59c4a9/R/predict.R#L48

But the param docs for `new_data` could mention: `` "If using a recipe preprocessor, you should not call `recipes::bake()` on the data ahead of time." ``
https://github.com/tidymodels/workflows/blob/2513121aebab1564970999d2380b98fbff59c4a9/R/predict.R#L19-L20
