### ISSUE TITLE
Do not allow fitted recipes

### ISSUE THREAD

**Issue by topepo** [tidymodels/workflows#179]
Another thing that I've seen is that people prep a recipe then use `add_recipe()`. Can we error when that happens and add something to the man file for `add_recipe()`? 

``` r
library(tidymodels)

training <- mtcars[1:20, ]
testing <- mtcars[21:32, ]

model <- linear_reg() %>%
  set_engine("lm")

workflow <- workflow() %>%
  add_model(model)

recipe <- recipe(mpg ~ cyl + disp, training) %>%
  step_log(disp) %>% 
  prep()

map_lgl(recipe$steps, is_trained)
#> [1] TRUE

workflow <- add_recipe(workflow, recipe)

fit_workflow <- fit(workflow, training)
```

<sup>Created on 2022-09-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
Maybe `recipes::is_trained()` should do `all(map_lgl(x$steps, is_trained))` if given a recipe. Then workflows can do

```r
if (recipes::is_trained(recipe)) {
  abort("Can't add a trained recipe to a workflow.")
}
```

**Comment by simonpcouch** [comment]
Unfortunately the `all(map_lgl(rec$steps, is_trained))` approach wouldn't do the trick either, as in the no-steps case:

``` r
library(recipes)

rec <- recipe(mpg ~ cyl, mtcars)
rec_trained <- recipe(mpg ~ cyl, mtcars) %>% prep()
  
all(purrr::map_lgl(rec$steps, is_trained))
#> [1] TRUE
all(purrr::map_lgl(rec_trained$steps, is_trained))
#> [1] TRUE
```

From the `print.recipe()` method, though, it looks like `"tr_info" %in% names(x)` is a flag we could look to:

``` r
"tr_info" %in% names(rec)
#> [1] FALSE
"tr_info" %in% names(rec_trained)
#> [1] TRUE
```

@EmilHvitfeldt, would you game for a PR that transitions `is_trained()` to a method with a `recipe` and `default` method?

<sup>Created on 2023-05-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by EmilHvitfeldt** [comment]
Are you looking for `fully_trained()`?

``` r
library(recipes)

rec <- recipe(mpg ~ cyl, mtcars)
rec_trained <- recipe(mpg ~ cyl, mtcars) %>% prep()

fully_trained(rec)
#> [1] FALSE

fully_trained(rec_trained)
#> [1] TRUE
```

**Comment by simonpcouch** [comment]
Perfect, thanks so much @EmilHvitfeldt!
