### ISSUE TITLE
CRAN failure with upcoming changes to `utils::packageVersion()`

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workflows#192]
A note on upcoming changes to `packageVersion()` from CRAN folks needs changes submitted soon. With the change "Have packageVersion() warn if not found and always return a (possibly NA) numeric version," they see:

> packages are no longer installable because their startup code assumes that
> packageVersion() throws an error in the not found case, and hence e.g.
>
>  should_register_tune_args_method <- tryCatch(
>    expr = utils::packageVersion("tune") >= "0.1.6.9001",
>    error = function(cnd) TRUE
>  )
>  if (should_register_tune_args_method) {
>    ...
>
> no longer works as intended. 
>
> ...
>
> We thus reverted the change for the time being, but can you please
> change your package code to work with the documented behavior of
> packageVersion()?
>
> Personally, I would use something like
>
>  should_register_tune_args_method <-
>    (nzchar(system.file(package = "tune")) &&
>     utils::packageVersion("tune") >= "0.1.6.9001")
>
> We would very much appreciate if you could make the changes as quickly
> as possible.

**Comment by DavisVaughan** [comment]
I'd consider just removing this entirely now that the version of tune we are checking for has been out for around a year

**Comment by simonpcouch** [comment]
Making public part of a discussion with @hfrick: after poking around blames for a moment, I'm convinced that we could register these in the usual way! It does seem like the only reason they were registered via `s3_register()` in the past is because of the tune migration part—when they were in tune beforehand, they were [registered in the usual way](https://github.com/tidymodels/tune/pull/420/files).
