### ISSUE TITLE
Create a unique ID for a model/workflow

### ISSUE THREAD

**Issue by DavZim** [tidymodels/workflows#30]
First of all, thank you for the good work, I really enjoy working with tidymodels and workflows in particular, it really improved my experience of doing ML in R!

What I currently miss is the possibility to create a unique ID for a model (e.g., by hashing the model using `digest::digest(model)`). The issue with using `digest()`, is that `model$fit` contains the elapsed training time (which of course changes every time), thus the hash is different and two identical models get different IDs (see also [this gist](https://gist.github.com/DavZim/0aef21c47721b7a703d85b0f164b34c1) for a comparison and a first working solution).

One issue I found with the simple solution I provided in the gist, is that when I save and load the model, some environments (e.g., quosures in steps) change address, thus the hash changes as well...

Having a way to create a unique and persistent ID for a model or workflow would help me to version my models and keep track of the models, the training data, and performance.

**Comment by topepo** [comment]
I think that the solution would be to use the `butcher` package to remove these elements so that it is deterministic/robust. We could add `axe_` methods for the time stamp and I think that the other `axe_` methods remove the environments from quosures (actually replace them with the base environment).

**Comment by DavZim** [comment]
I'm not too familiar with the butcher package. So far I haven't found a function that axes the fit. However, `axe_env()` does replace the environments of the quosures. 

Do I understand `axe_env` correctly, that it needs to be executed on the specific item and not the main list/model (where it then iterates through and finds/replaces the quosures)?

**Comment by DavisVaughan** [comment]
I think creating a unique ID off the workflow object itself is less stable vs having some infrastructure like https://vetiver.tidymodels.org that can help you monitor model versions through pins, or some other ID that is created separately from the workflow
