### ISSUE TITLE
response from predict()? 

### ISSUE THREAD

**Issue by Athospd** [tidymodels/workflows#35]
What do you guys think about a feature from predict() for bring up the outcome columns as well? Like `predict(workflow_fit_obj, test_data, type = "prob", outcomes = TRUE)`

Once I had a recipe that would do tons of transformations on the outcome and the code to retrieve it in the test step became kinda verbose.

```
# not reproducible! 
my_predict <- function(workflow_fit_obj) {

  outcome <- workflow_fit_obj %>% 
    extract_recipe() %>% 
    bake(new_data) %>%
    pull(outcome_var)
  
  predict(workflow_fit_obj, new_data) %>% 
    mutate(truth = outcome)
}
```

And I guess it would be a widely used feature because one wants to calculate metrics in test data pretty often.
Btw, it woul also spare some computations once predict() already runs recipes::bake()!

**Comment by topepo** [comment]
I don't think that we'll do this. 

It only saves an additional `bind_cols()` line. Also, when predicting unknowns, the outcome data are not available so we'd have to code up some special cases for that. 

On the bright side, the `tune_*` and `fit_resamples()` functions in `tune` can return the predictions with the observed outcomes (and row number too)

**Comment by Athospd** [comment]
Ok @topepo , I PRed before read your considerations, I am sorry. I realized that `hardhat::forge()` already had the `outcomes` arg and I felt confident enough to invest time to make this suggestion.

When you say "unknowns" is regarding the predictors or the outcomes? Cuz 

- the default could still be to NOT return outcomes; and
- it would give an error if outcomes = TRUE and there is no outcome column in the new_data. (because it doesn't make sense).

I'm afraid this outcomes = TRUE would be appealing when teaching, I had this experience yesterday.

what do you think?

**Comment by DavisVaughan** [comment]
Sorry @Athospd, I don't think I want to make this change. I think that `predict()` should purely be about getting a predicted outcome back. Most of the time when used outside of the context of tune I'd imagine that you won't have the outcome on hand anyways. I appreciate you putting in work in the PR though!

**Comment by topepo** [comment]
@Athospd No worries. By unknowns I meant the case when we are predicting new samples where the outcome is not known.

It might make sense to make an `broom::augment()` method to do something like what you want.

**Comment by Athospd** [comment]
I agree, guys!!
