### ISSUE TITLE
bars in printed output depend on window width

### ISSUE THREAD

**Issue by topepo** [tidymodels/workflows#38]
In the IDE, the length of the bars created by the print method are largely determined by how wide the window (and not the `width` option). 

For example: 

```r
> library(workflows)
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] workflows_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       tidyr_1.0.2       
 [3] crayon_1.3.4       dplyr_0.8.99.9002 
 [5] R6_2.4.1           lifecycle_0.2.0   
 [7] magrittr_1.5       pillar_1.4.3      
 [9] rlang_0.4.5.9000   parsnip_0.0.5.9000
[11] rstudioapi_0.11    vctrs_0.2.99.9011 
[13] generics_0.0.2     tools_3.6.1       
[15] glue_1.4.0         purrr_0.3.3       
[17] compiler_3.6.1     pkgconfig_2.0.3   
[19] tidyselect_1.0.0   tibble_2.1.3      
> 
> options(width = 50)
> 
> workflow()
══ Workflow ══════════════════════════════════════
Preprocessor: None
Model: None
> # widen console panel in IDE
> 
> workflow()
══ Workflow ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Preprocessor: None
Model: None
```

**Comment by DavisVaughan** [comment]
I'm not sure I understand, why wouldn't you want it to be the console width?

You can use the `cli.width` option as a replacement for `width` right now. The way cli works is that it looks to see if the `cli.width` option is set first, then it looks to the `RSTUDIO_CONSOLE_WIDTH` environment variable, then it finally looks to the `width` option.

That logic is in `cli:::console_width`.

@gaborcsardi is there a reason you look to the `width` option _after_ the RStudio console width env var? Would it make sense to use the `width` option, if set, before falling back to the console width?

```r
> workflows::workflow()
══ Workflow ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Preprocessor: None
Model: None
> 
> options(width = 20)
> 
> # does nothing
> workflows::workflow()
══ Workflow ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Preprocessor: None
Model: None
> 
> options(cli.width = 20)
> 
> workflows::workflow()
══ Workflow ════════
Preprocessor: None
Model: None
```

**Comment by gaborcsardi** [comment]
I _think_ the env var is also set in the terminal and the build pane, but the width is just the default there.

**Comment by gaborcsardi** [comment]
But I don't mind changing this, so if you think it is better to take the `width` option, we can do that as well.

**Comment by topepo** [comment]
It's unexpected that the IDE would affect the results. For example, when we serve a blogdown site the results look different on the website and the difference is based on the state of the IDE window. It's hard to figure that out if you didn't know. 

Also, we don't (usually) programmatically set that so having a means to ensure a consistent bar width would be great.

**Comment by DavisVaughan** [comment]
Yea it looks like the IDE changes the `width` option whenever you widen the Console pane. So even if you set it with `options(width = 20)`, the next time you widen the pane it will change again.

Setting the cli.width with `options(cli.width = 20)` is a more permanent solution. I don't think there is anything else to do here.
