### ISSUE TITLE
predict() does not work if fitted workflow object has been saved as rds. 

### ISSUE THREAD

**Issue by fderyckel** [tidymodels/workflows#45]
I have used this page for help: 
https://workflows.tidymodels.org/reference/predict-workflow.html

the workflow is a nlp task using lasso and textrecipes. 

I fitted a workflow object using fit(wf, train_data)
Then I use the workflow object with predict(wf, newdata).  no error.  It works as expected. 

If I saved the workflow object using write_rds().  Close the session, clean all objects, restart r. 
I read the workflow object using read_rds(wf.rds), then apply predict to that object.  It gives me error. 

> model_lasso_enhanced <- read_rds("disaster_tweets/models/model_lasso_enhanced.rds")
> yo <- predict(model_lasso_enhanced, new_data = test, type = "prob")
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "c('lognet', 'glmnet')"
> class(model_lasso_enhanced)
[1] "workflow"

**Comment by fderyckel** [comment]
OK I got it.  
That is because when calling predict() in a new session, the library(glmnet) wasn't on.  Although tidyverse, tidymodels, textrecipes, tidytext were called, glmnet wasn't explicitly called.  

These libraries are loaded automatically in the workflow with the set_engine().   But they are not automatically loaded when calling back predict() later on.  

Thanks again for that awesome set of packages.  Still tinkering with it all.

**Comment by topepo** [comment]
We'll be fixing that soon: tidymodels/parsnip#308

**Comment by fderyckel** [comment]
I see.  Thanks again for all your work with your team.  Phenomenal!

**Comment by DavisVaughan** [comment]
We can track this with the parsnip issue

**Comment by andrewcstewart** [comment]
So is `write_rds` / `read_rds` the recommended way to serialize/deserialize a workflow?

**Comment by topepo** [comment]
yes unless it involves a model like keras that stores the data in memory (and not locally in the R object).
