### ISSUE TITLE
Save a finalised workflow

### ISSUE THREAD

**Issue by fieldofnodes** [tidymodels/workflows#59]
Firstly, I do not have a set of code to show my situation.  This is basically a question. Apologies if it has been answered and I have not read it just yet.

Basically, I am working on a classification project using Tidymodels.

I have split the data, set some recipes, established the model, performed the resampling and tune method and have finalised the workflow.  I will be using the workflow to predict future data and I want to be able to save the finalised model to disc/server and then load it as if I were loading a CSV. 

That way when I have users load data to get a prediction, they just wait for the prediction and not for the fit and all the other steps that happen before.

Is this currently possible?

Thanks

**Comment by juliasilge** [comment]
What you are talking about doing is **deploying** your model and how you go about doing that depends on what kind of model you have trained. Deploying a finalized tidymodels workflow has about the same issues involved as deploying any model created in R. 

- If it's a linear model, you can just extract the coefficients and you could write them as a CSV. 
- If you trained it in Spark, you can keep the Spark object. 
- If you need to deal with the R object itself, you can look into options such as [building an API](https://www.rplumber.io/) to serve predictions.

I recommend the resources available at [**Put R in Prod**](https://putrinprod.com/) as well. What you want to look for is a deployment option that fits the kind of model you have built and the system where predictions need to be served.

**Comment by fieldofnodes** [comment]
Thanks for the feedback @juliasilge  my model is a random forest with the Ranger package. I will look into those links you shared.

**Comment by juliasilge** [comment]
If you are working with data in some flavor of SQL database, check out [tidypredict](https://db.rstudio.com/tidypredict/) for deploying a ranger model.
