### ISSUE TITLE
extend repair_call() to workflows and fix formula

### ISSUE THREAD

**Issue by topepo** [tidymodels/workflows#61]
From tidymodels/tidymodels.org#174

Ah, I think the formula has been repaired for parsnip but **not** for workflows. 

Check this out:

``` r
library(tidymodels)
#> ── Attaching packages ────────────────────────────────────── tidymodels 0.1.1 ──
#> ✓ broom     0.7.0      ✓ recipes   0.1.13
#> ✓ dials     0.0.8      ✓ rsample   0.0.7 
#> ✓ dplyr     1.0.0      ✓ tibble    3.0.3 
#> ✓ ggplot2   3.3.2      ✓ tidyr     1.1.0 
#> ✓ infer     0.5.3      ✓ tune      0.1.1 
#> ✓ modeldata 0.0.2      ✓ workflows 0.1.2 
#> ✓ parsnip   0.1.2      ✓ yardstick 0.0.7 
#> ✓ purrr     0.3.4
#> ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
library(partykit)
#> Loading required package: grid
#> Loading required package: libcoin
#> Loading required package: mvtnorm

data(kyphosis, package = "rpart")

tree_spec <- 
  decision_tree(
    cost_complexity = 1e-10,
    tree_depth = 4
  ) %>% 
  set_engine("rpart") %>% 
  set_mode("classification")

wf_fit <- workflow() %>%
  add_model(tree_spec) %>%
  add_formula(Kyphosis ~ Age + Number + Start) %>%
  fit(data = kyphosis) %>%
  pull_workflow_fit() 

wf_fit$fit$call
#> rpart::rpart(formula = ..y ~ ., data = data, cp = ~1e-10, maxdepth = ~4)
```

<sup>Created on 2020-07-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Looks like the formula is [still not being preserved](https://www.tidyverse.org/blog/2020/07/parsnip-0-1-2/#better-call-objects) for workflows.

**Comment by DavisVaughan** [comment]
Hmm, I'm not entirely sure what can be done here. Remember that workflows lets hardhat do the preprocessing requested in `add_formula()`, so really its `parsnip::fit_xy()` that gets called. I guess that internally needs to switch from XY - > Formula to pass along to rpart, and that is where parsnip just inserts a formula of `..y ~ .`

Since we really are using `fit_xy()` here, I'm not sure how to make parsnip aware of the formula that was used

**Comment by DavisVaughan** [comment]
Separately: If `repair_call()` was to be extended to workflow objects, then we'd probably need to make it generic in parsnip so we can create a `repair_call.workflow` method here
