### ISSUE TITLE
Remove Training Data From Workflow Object

### ISSUE THREAD

**Issue by jared-fowler** [tidymodels/workflows#83]
Hey,

Is there any easy way to remove all meta data (such as training data, and anything else which is not needed for scoring) from the workflow object before saving/deploying the workflow?

**Comment by juliasilge** [comment]
This is a great question @jared-fowler! We don't currently have methods for this kind of stripping out and reducing object size for workflows. If model object size for prediction is a concern for you right now, you might check out the [butcher](https://github.com/tidymodels/butcher/) package, which currently works for parsnip models (but not, like I mentioned, for workflows).

It is possible that we would work on extending this in the future, depending on prioritization.

**Comment by jared-fowler** [comment]
Thanks @juliasilge! Ill have a look into the butcher package, I would love to see a similar feature for workflows, l'll keep my eye out 👍.
