### ISSUE TITLE
Uninformative error if predictors are specified wrongly in add_variables()

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/workflows#93]
I'm not quite sure if this is a workflows issue or tidyselect issue.

If you are not quite familiar with the tidyselect way of doing things you might try to specify predictors as you do in formula expressions. 

Maybe a simple check and to see if `+` is used would be sufficient

``` r
library(workflows)
library(parsnip)

spec_lm <- linear_reg() %>%
  set_engine("lm")

workflow <- workflow() %>%
  add_model(spec_lm) %>%
  add_variables(
    outcomes = mpg,
    predictors = cyl + disp
  )

fit(workflow, mtcars)
#> Error: object 'cyl' not found
```

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
I think this is an error that we are probably just going to have to live with. I've asked Lionel in the past if tidyselect could improve on this kind of error message, and it happens too low in the stack for them to be able to change it in a robust way. I'd rather not start walking the AST for things like this, it just opens up a big can of worms that I don't want to get into.
